# Generated by Django 5.2.7 on 2026-02-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STTModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Model identifier (e.g., base, small, medium)', max_length=100, unique=True)),
                ('model_type', models.CharField(default='whisper', help_text='Type of STT model (e.g., whisper)', max_length=50)),
                ('device', models.CharField(default='cpu', help_text='Device to run on (cpu, cuda)', max_length=20)),
                ('compute_type', models.CharField(default='int8', help_text='Compute precision (int8, float16, float32)', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Is this the currently active model?')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default model?')),
                ('description', models.TextField(blank=True, help_text='Description of the model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'STT Model',
                'verbose_name_plural': 'STT Models',
                'ordering': ['name'],
            },
        ),
    ]
