# Generated by Django 5.2.7 on 2026-02-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NERModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Model identifier (e.g., slot_model)', max_length=100, unique=True)),
                ('model_type', models.CharField(default='slot-filling', help_text='Type of NER model', max_length=50)),
                ('model_path', models.CharField(help_text='Path to model directory', max_length=255)),
                ('device', models.CharField(default='cpu', help_text='Device to run on (cpu, cuda)', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Is this the currently active model?')),
                ('status', models.CharField(default='created', help_text='Model status (active, created, training)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NER Model',
                'verbose_name_plural': 'NER Models',
                'ordering': ['-created_at'],
            },
        ),
    ]
